---
- name: Copy Docker Repo for CentOS
  get_url:
    url: "{{ docker_repo_url }}"
    dest: "/etc/yum.repos.d/docker-ce.repo"

- name: Install Containerd.io
  dnf: 
    name: "{{ docker_containerd_url }}"
    state: present

- name: Install Python3
  dnf:
    name:
      - python3
      - python3-devel
      - python3-pip
    state: latest
    update_cache: true

- name: Install Docker-CE
  dnf:
    name: 
      - docker-ce
    state: latest
    update_cache: true

- name: Enable and Start Docker Service
  systemd:
    name: docker
    state: started
    enabled: true

- name: Firewall - Add docker0 to Trusted Zone
  firewalld:
    interface: docker0
    zone: trusted
    state: enabled
    permanent: true
    immediate: yes
  tags: 
    - firewall

# - name: Firewall - Enable Masquerade on Trusted Zone
#   firewalld:
#     masquerade: "no"
#     zone: trusted
#     state: enabled
#     permanent: true
#     immediate: yes
#   tags: 
#     - firewall

- name: Install Docker Python Requirements
  pip:
    name: "{{ item }}"
    executable: pip3 
    state: latest 
  loop:
    - docker
    - jsondiff
    - pyyaml
    - docker-compose
    - zabbix-api
    - pexpect
  tags:
    - install
    - pip