---
- name: Create Custom Roles
  uri:
    url: "http://localhost:9200/_security/role/{{ item.name }}"
    url_username: elastic
    url_password: "{{ elk.users.elastic.password }}"
    method: POST
    body_format: json
    body:
      cluster: "{{ item.cluster }}"
      indices: "{{ item.indices }}"
  loop: "{{ elk.roles }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - roles

- name: Create Custom Users
  uri:
    url: "http://localhost:9200/_security/user/{{ item.key }}"
    url_username: elastic
    url_password: "{{ elk.users.elastic.password }}"
    method: POST
    body_format: json
    body:
      password: "{{ password }}"
      roles: "{{ roles }}"
      full_name: "{{ full_name }}"
  loop: "{{ elk.users | dict2items }}"
  vars:
    user: "{{ item.key }}"
    password: "{{ item.value.password }}"
    roles: "{{ item.value.roles }}"
    full_name: "{{ item.value.full_name }}"
  loop_control:
    label: "{{ user }}"
  when:
    - user not in built_in_users
  tags:
    - passwords
    - roles

