---
- name: Create Portainer Volume
  docker_volume:
    name: portainer_data

- name: Start Portainer
  docker_container:
    name: portainer
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    restart_policy: unless-stopped
