---
docker_repo_url: "https://download.docker.com/linux/centos/docker-ce.repo"
docker_containerd_url: "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.10-3.2.el7.x86_64.rpm"