---
elasticsearch_image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
kibana_image: docker.elastic.co/kibana/kibana:7.6.2
elk_env:
  elasticsearch:
   discovery.type: "single-node"
   ES_JAVA_OPTS: "-Xms512m -Xmx512m"
   xpack.security.enabled: "true"
   xpack.monitoring.collection.enabled: "true"
   XPACK_MONITORING_ENABLED: "true"
  kibana:
    SERVER_NAME: "{{ elk.kibana.name }}"
    XPACK_MONITORING_ENABLED: "true"
    ELASTICSEARCH_HOSTS: "http://{{ elk.elasticsearch.name }}:9200"
  logstash:
elk_volumes:
  elasticsearch: | 
    [
    {% for volume in elk.elasticsearch.volumes %}
      "{{ volume.name }}:{{ volume.mountpoint }}{% if volume.mode is defined %}:{{ volume.mode }}{% endif %}",
    {% endfor %}
    ]